export const constantes = {
    NOMBREPROCESOCONTRATACIONFINALIZADAALVERESTADO: 'fin bdt',
    NOMBREPROCESOCONTRATACIONFINALIZADAALCOMPLETAR: 'mensaje finalizado ',
    ORIGEN_BANKIA_CONNECT: 'PASCON',
    ID_EVENTO_BANKIA_CONNECT: 'eventoTercerosPASCON',
    ID_EVENTO_TAREA_DOC_FINALIZADA: 'eventoTareaDocFinalizada',
};
