export const FILE_CONTEXT = {
    STATE: {
        0: 'EMPTY',
        1: 'LOADING',
        2: 'DONE',
    },
    SENDING_TYPE: {
        READ_AS_BINARY_STRING: 'readAsBinaryString',
        READ_AS_ARRAY_BUFFER: 'readAsArrayBuffer',
        READ_AS_TEXT: 'readAsText',
        READ_AS_DATA_URL: 'readAsDataURL',
        NONE: 'none',
    },
    VALID_MIME_TYPES: {
        AUDIO_AAC: 'audio/aac',
        BINARY: 'application/octet-stream',
        VIDEO_AVI: 'video/x-msvideo',
        VIDEO_MPEG: 'video/mpeg',
        HTML: 'text/html',
        XML: 'application/xml',
        CSS: 'text/css',
        JSON: 'application/json',
        JAVASCRIPT: 'application/javascript',
        CSV: 'text/csv',
        WORD_DOC: 'application/msword',
        WORD_POWER_POINT: 'application/vnd.ms-powerpoint',
        WORD_POWER_EXCEL: 'application/vnd.ms-excel',
        PDF: 'application/pdf',
        OPEN_DOCUMENT_DOC: 'application/vnd.oasis.opendocument.text',
        OPEN_DOCUMENT_CALC: 'application/vnd.oasis.opendocument.spreadsheet',
        OPEN_DOCUMENT_PRESENTATION: 'application/vnd.oasis.opendocument.presentation',
        IMAGE_GIF: 'image/gif',
        IMAGE_PNG: 'image/png',
        IMAGE_JPEG: 'image/jpeg',
        IMAGE_JPG: 'image/jpg',
        IMAGE_ICON: 'image/x-icon',
        SVG: 'image/svg+xml',
        I_CALENDAR: 'text/calendar',
        JAVA_JAR: 'application/java-archive',
        RAR: 'application/x-rar-compressed',
        ZIP: 'application/zip',
        ZIP_7: 'application/x-7z-compressed',
    },
};
